version: '3'

services:
  nginx:
    image: nginx:1.22-alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/code
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php
      - db

  php:
    image: php:8.2-fpm
    container_name: symfony_php
    working_dir: /code
    volumes:
      - ./:/code
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: symfony_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - ~/sf_terra_quest/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony_phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
